<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterButton</name>
   <tag></tag>
   <elementGuidId>7f0c1094-b20c-47bb-bc35-ee40c2768501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@text='Filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@text='Filter']</value>
      <webElementGuid>aef75d8f-580a-4fa0-a4d5-0effa7cffdcf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
