<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailTextField</name>
   <tag></tag>
   <elementGuidId>c07a7548-519a-4f1f-865a-6fb7cf8537f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.View[@resource-id='emailValidation']/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.View[@resource-id='emailValidation']/android.widget.EditText</value>
      <webElementGuid>f1721fbd-d102-40bd-99dc-60bc5b7ed2eb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
