<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupOkButton</name>
   <tag></tag>
   <elementGuidId>96b814ca-2825-4a18-a67f-6b447adab7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@text='OK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@text='OK']</value>
      <webElementGuid>77d1a90a-9227-4774-bfb2-a7c1a04db11a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
